vplayer/streams/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views
from django.conf import settings

app_name = 'player'


urlpatterns = [
    path("",views.window,name='window'),
    path("create_me",views.create_me,name='create_me'),
]

vplayer/vplayer/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns 

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('streams.urls')),
    
]

urlpatterns +=staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vplayer/streams/models.py
from django.db import models

# Create your models here.

vplayer/streams/views.py
from django.shortcuts import render

from django.http.response import FileResponse
from django.core.files.storage  import FileSystemStorage

import xml.etree.ElementTree as ET
import xlsxwriter


def window(request):
    return render(request,'player/window.html')

def create_me(request):
     if request.method=='POST':   
        ip_file=request.FILES['ipfile']
        fs=FileSystemStorage()
        print("-----------",ip_file,type(ip_file.name),ip_file.name)
        fs.save(ip_file.name,ip_file)
        
        outworkbook=xlsxwriter.Workbook("./assets/files/out.xlsx")
        ot=outworkbook.add_worksheet()
        ippath="./media/"+ip_file.name;
        
        tree = ET.parse(ippath)
        root = tree.getroot()
        c=1
        cell_format = outworkbook.add_format({'bold': True})
        cell_format.set_align('center')
        cell_format.set_font_name('Cambria')



        
        header=['Date', 'Transaction Type', 'Vch No.', 'Ref No', 'Ref Type', 'Ref Date', 'Debtor', 'Ref Amount', 'Amount', 'Particulars', 'Vch Type', 'Amount Verified']
        ot.write_row(0,0,header)

        for i in root.iter('VOUCHER'):
            if i.attrib['VCHTYPE']=='Receipt':

                raw_date=i.find('DATE').text
                date=raw_date[6:8]+'-'+raw_date[4:6]+'-'+raw_date[0:4]

                vch_no=i.find('VOUCHERNUMBER').text
                main_name=i.find("PARTYLEDGERNAME").text

                for elem in i.iter('ALLLEDGERENTRIES.LIST'):
                    debtor=particulars=elem.find('LEDGERNAME').text
                    if debtor==main_name:
                        parent=True
                        trn_type="Parent"
                        amount_verified="NA"
                        cell=c
                    else:
                        trn_type="Other"
                        debtor=particulars=elem.find('LEDGERNAME').text
                        amount_verified="NA"
                    chk=amount=elem.find('AMOUNT').text
                    ref_amount="NA"
                    ref_type="NA"
                    ref_no="NA"
                    ref_date="NA"
                    
                    vch_type=i.find('VOUCHERTYPENAME').text

                    res=[date,trn_type,vch_no,ref_no,ref_type,ref_date,debtor,ref_amount,amount,particulars,vch_type,amount_verified]
                    ot.write_row(c,0,res)
                    c=c+1
                    sums=0

                    for q in elem.iter('BILLALLOCATIONS.LIST'):
                
                        if q.find("AMOUNT")!=None:
                            amount="NA"
                            ref_amount=q.find('AMOUNT').text
                            ref_type=q.find("BILLTYPE").text
                            ref_no=q.find('NAME').text
                            trn_type="Child"
                            ref_date=""
                            amount_verified="NA"
                            ref_date=""

                            debtor=particulars=i.find('PARTYLEDGERNAME').text
                            vch_type=i.find('VOUCHERTYPENAME').text
                            res=[date,trn_type,vch_no,ref_no,ref_type,ref_date,debtor,ref_amount,amount,particulars,vch_type,amount_verified]
                            ot.write_row(c,0,res)
                            c=c+1
                            sums=float(ref_amount)+sums;

                    if float(sums)==float(chk):
                        ot.write(cell,11,"YES")

        print("count=",c)
        outworkbook.close()
        

        f=open("./assets/files/out.xlsx",'rb')
        path="./assets/files/out.xlsx"
        resp = FileResponse(f)
        resp['Content-Disposition'] = 'attachment; filename="foo.xls"'

        return resp

vplayer/streams/templates/player/index.html
{% load static %}
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
       

            yo wasup
       
            <video width="320" height="240" controls>
                <source src="{% static 'video/Craftsmanship-1.m4v' %}" type="video/mp4">
               
                Your browser does not support the video tag.
                </video>        

second one 
                <video width="320" height="240" controls>
                    <source src="http://127.0.0.1:8000/player" type="video/mp4">
                   
                    Your browser does not support the video tag.
                    </video>        
        <script src="" async defer></script>
    </body>


    <script>
  
        var eventSource  = new EventSource("{% url 'player:player' %}");
        console.log(eventSource)
    </script>
</html>

vplayer/streams/templates/player/window.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>XML-XLS</title>
</head>
<body>
    <center><h1>XML to XLSX</h1></center>
    <h3>Upload an xml file </h3>

    <form action="{% url 'player:create_me'%}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
    <input type="file" name="ipfile" id="ipfile">
    <input type="submit" value="Create">
    </form>
</body>
</html>